version: '3'
services:
  doh:
    build: doh
    depends_on:
      - nameserver
    restart: "always"
    labels:
      - "traefik.frontend.entryPoints=https"
      - "traefik.domain=usableprivacy.net"
      - "traefik.frontend.rule=Host:adfree.usableprivacy.net"
      - "traefik.application.port=8053"
  nameserver:
    build: nameserver
    restart: "always"